### ISSUE TITLE
missing 1 required keyword-only argument: 'intents'

### ISSUE THREAD

**Issue by KozacheShapka** [Raptor123471/DingoLingo#113]
![image](https://user-images.githubusercontent.com/79427139/187084142-e9fdec70-c038-45a1-ab22-5cd4a2339dda.png)
help!
I'm using python3.9 on Ubuntu 18.04

**Comment by RafaelSolVargas** [comment]
Looking in this another [issue](https://github.com/Raptor123471/DingoLingo/issues/110) we see that the problem occurred because this code is not compatible with pycord 2.0 and the version in requirements.txt isn't locked.
Try installing an older version of pycord (pip install "py-cord<2.0.0").

**Comment by EliFebres** [comment]
I was able to get it to work by installing an older version of discord.py.
I wouldn't try anything after (discord.py==1.7.3)

**Comment by KozacheShapka** [comment]
> I was able to get it to work by installing an older version of discord.py. I wouldn't try anything after (discord.py==1.7.3)

thanks, this method worked
