### ISSUE TITLE
Not Working on Heroku

### ISSUE THREAD

**Issue by EliFebres** [Raptor123471/DingoLingo#114]
I can get the program to play perfectly fine on my own PC but cannot get it to play music when hosted on Heroku
•	Setup the config file correctly
•	Added both build packages (ffmpeg and libopus)
The program boots with no errors, joins discord with no errors, downloads songs and says “playing” but does not light-up green in discord and does not play song.

P.S. if you want to get the program to work download these package versions
•	discord.py==1.7.3
•	py-cord==1.7.3

**Comment by RafaelSolVargas** [comment]
In this [issue](https://github.com/RafaelSolVargas/Vulkan/issues/25) i discovered a problem with the ffmpeg package, try the solution that i showed there.
Let me know if you get it.

**Comment by EliFebres** [comment]
that worked thank you!

**Comment by solaluset** [comment]
Oh, I also had this problem, but resolved it by moving to containerised building, haha
