### ISSUE TITLE
Nothing gets added to queue

### ISSUE THREAD

**Issue by EdwinKorner** [Raptor123471/DingoLingo#127]
When I send the play command the bot joins and sends a message that the song has been added to the queue, but the bot doesn't play anything and if I use the queue or skip command it says that the queue is empty. I've tried to look through the code and find the solution but since I'm new to python I can't find anything that seems to be wrong

**Comment by solaluset** [comment]
I think that the code is outdated. Can you try [my fork](https://github.com/Krutyi-4el/DandelionMusic) and see if it works for you?

**Comment by EdwinKorner** [comment]
I have the exact same problem in your fork aswell, do you have any idea what the problem could be?

**Comment by EdwinKorner** [comment]
Changed some of the packages versions and now it works! Thanks for the help :)
