### ISSUE TITLE
Previous command bug

### ISSUE THREAD

**Issue by XPr0methiumX** [Raptor123471/DingoLingo#33]
Hey, there's a bug in the previous command, when you play the first two songs, if you skip the first one and go to the next and then type '!prev' then it doesn't do anything and returns this error :
Task exception was never retrieved
future: <Task finished name='Task-132' coro=<AudioController.play_song() done, defined at /home/runner/Music-1/musicbot/audiocontroller.py:70> exception=AttributeError("'str' object has no attribute 'info'")>
Traceback (most recent call last):
  File "/home/runner/Music-1/musicbot/audiocontroller.py", line 73, in play_song
    if song.info.title == None:
AttributeError: 'str' object has no attribute 'info'

Also, it adds the song that you wanted to play before in the queue and basically breaks the queue into unlimited songs of the same thing until you clear the queue. If possible, please give me your discord so that I can provide you with screenshots and any help would be appreciated, Thanks!

**Comment by Raptor123471** [comment]
Waiting for @XPr0methiumX to confirm fix on the [PREV_FIX](/Raptor123471/DingoLingo/tree/prev_fix) branch.
