### ISSUE TITLE
add a lyrics command?

### ISSUE THREAD

**Issue by SILENTK28** [Raptor123471/DingoLingo#36]
this isn't an issue but a lyrics command would be great

**Comment by Raptor123471** [comment]
How are you imagining this command would function?  In my opinion this would add complexity and another dependency for a command that would likely see little use.

**Comment by nuggetcatsoftware** [comment]
i think ill work on one and see if it works technically its not very easy

**Comment by Anarbb** [comment]
Hey, maybe you can use this [https://pypi.org/project/lyricsgenius/](https://pypi.org/project/lyricsgenius/) and make the user get the API key for it, cus some people like to do karaoke and this is very useful for that.

**Comment by Raptor123471** [comment]
I have never seen people do discord karaoke so I'm not familiar with the process. Can you describe how the interaction would go? If lyric timing is required I wouldn't even know where to start.

**Comment by Anarbb** [comment]
Not really that would be way too hard to implement i would believe, unless the API provides timestamps to each lyric to sync with the song, but it would be a good feature. But just dropping the lyrics all at once is good enough
