### ISSUE TITLE
Bot clears queue when switching channels

### ISSUE THREAD

**Issue by Anarbb** [Raptor123471/DingoLingo#44]
I'm not sure if this is a bug or a feature but when i use the command -changechannel it clears the queue, it would be useful to keep the same song playing even after changing the channel

**Comment by Raptor123471** [comment]
I feel like this is a very rare scenario. How often does this situation pop up and why? I'm trying to gauge the general usefulness of adding this feature. If this were to be implemented the current playing song would have to be restarted in the changed channel.
