### ISSUE TITLE
Add feature to self disconnect when the bot's inactive

### ISSUE THREAD

**Issue by JustThinker1** [Raptor123471/DingoLingo#46]
Hi,

May you add feature to self disconnect when the bot's inactive? something like a timeout if the bot is inactive for 5 minutes
because the bot is not automatically disconnected and most of times no one manually disconnect it

Sincerely

**Comment by Raptor123471** [comment]
Feature planned in linked pull request

**Comment by Raptor123471** [comment]
You can test this feature out in the staging branch early. Check out the 'VC_TIMEOUT' config option. Let me know if you find an issue before I do.

**Comment by JustThinker1** [comment]
Well, It worked but there is a bit little issue,
If anyone used "$loop" command on a music, then the bot will never leave the voice channel even if there is no one hearing the music.

May you make the timer start counting after no one is exist in the voice channel?

Sincerely

**Comment by Raptor123471** [comment]
Thanks for testing out the staging branch, it is a big help. I agree that it should check if anyone is in the VC. I'll update you here when you can try it out.

**Comment by Raptor123471** [comment]
I added the timeout on empty VC to the staging branch, you can try it out now if you want. Please note the changes made to the config.

**Comment by JustThinker1** [comment]
Thanks, It worked well, but there is an issue that happen after the last changes

Now if someone used "$loop" and left the VC, the bot will leave The VC normally after the timeout BUT after that when someone else (or the same person) try to connect the bot again to play a new music, the bot will NEVER play any music, It will just say "Added to queue" and will never play it.

I really appreciate your efforts,
Sincerely

**Comment by Raptor123471** [comment]
This one was tricky to track down but I think it is fixed with the latest commit. The 'stop_player' function was not ending the loop.

**Comment by JustThinker1** [comment]
Thanks a lot! It is fixed now like a magic with the latest commit.

Sincerely

**Comment by Raptor123471** [comment]
Thanks for helping me test out the new features. I'm going to test this for a while myself then merge the PR. This issue will be closed when that happens.
