### ISSUE TITLE
Cogs with no setup

### ISSUE THREAD

**Issue by JeeboCS** [Raptor123471/DingoLingo#48]
Every time the main bot gets opened, the only error that comes through is "module config has no setup". Even unmodified (except for tokens) it still has this issue.

**Comment by Raptor123471** [comment]
Can you post the full error here? I am not able to reproduce the issue on multiple instances. Check to make sure you have the latest bot version, an updated python install, look for possible modules conflicting with the name `config` and reinstall your modules with the `--force-reinstall`. OS info would be helpful also.

**Comment by JeeboCS** [comment]
`No module named 'musicbot'
No module named 'musicbot'
No module named 'musicbot'
Traceback (most recent call last):
 File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py" line 612, in _load_from_module_spec setup = getattr(lib, 'setup')
AttributeError: module 'config' has no attribute 'setup'

During handling of the above exception, another exception occured

Traceback (most recent call last):
 File "C:\Users\rektg\Documents\Discord Bot\run.py", line 156, in <module> client.load_extension(f'cogs.{filename[:-3]}')
 File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py" line 678, in load extension self._load_from_module_spec(spec, name)
 File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py" line 615, in _load_from_module_spec raise errors.NoEntryPointError(key)
discord.ext.commands.error.NoEntryPointError: Extension 'config" has no 'setup' function.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000017EEDA02760>`

I will reinstall my modules. Windows 10 Pro 19042.1237

**Comment by Raptor123471** [comment]
Can you take a screenshot of your bot's folder structure? These are all directory local imports so there should be no issue importing them. I'll check your response in the morning

**Comment by JeeboCS** [comment]
![github 2](https://user-images.githubusercontent.com/91166599/134280368-4de9c832-81d6-4c0c-ac35-cb90cc31920f.PNG)
![github 1](https://user-images.githubusercontent.com/91166599/134280369-745bf0e7-5960-42eb-be06-b66d9d91fc4d.PNG)
I am opening it by double clicking it.

**Comment by Raptor123471** [comment]
The bot is intended to run with it's stock directory structure. If you intend to modify it like this you will need to edit the imports and paths to the new locations.

**Comment by JeeboCS** [comment]
The issue is, when I ran it stock, it still came up with the same errors.

**Comment by Raptor123471** [comment]
Cannot reproduce, Issue is with client setup/modification.
