### ISSUE TITLE
When an improper token is passed, or the bot is stopped, the aiohttp session remains unclosed.

### ISSUE THREAD

**Issue by TheOnlyWayUp** [Raptor123471/DingoLingo#60]
Title, only happens at times when I ctrl c the bot but happens consistently when an improper token is passed. I'm not sure if this also happens in dpy but I've never noticed it. Also, you did a great job with the bot, it exceeds expectations, has a great config and is well made overall, also nice how it registers all guilds on start. Gj :D

**Comment by Raptor123471** [comment]
No response
