### ISSUE TITLE
Any way to make the bot not disconnect after a certain period of time?

### ISSUE THREAD

**Issue by MineDudeYT** [Raptor123471/DingoLingo#73]
Hi! I was wondering if there's any way to make the bot not disconnect from a vc after a certain period of time since I'd like to make a vc that plays a specific playlist 24/7.

**Comment by Raptor123471** [comment]
@MineDudeYT 

Use the settings command in your server to set `vc_timeout` to False. See example below:

![image](https://user-images.githubusercontent.com/9324119/145724964-ea4396d5-ac62-4a34-9369-0725db06468e.png)

See the wiki documentation for the settings command here:
https://github.com/Raptor123471/DingoLingo/wiki/Settings-Command

**Comment by Raptor123471** [comment]
No response
