### ISSUE TITLE
Bot playing from youtube when passing spotify link

### ISSUE THREAD

**Issue by TheSiman** [Raptor123471/DingoLingo#74]
The bot tries to use youtube when i pass spotify link as a source. I have both SPOTIFY_ID and SPOTIFY_SECRET set in config.py (but the behaviour is the same if i leave both fields empty). This causes me issues because of youtube age restriction (and also the fact that the redirection often leads to music videos that have extra stuff aside from music), i know of the cookie workaround, but i want to know if i am doing something wrong or if this is the intended behaviour or maybe something that is not yet fully implemented. Sorry if it's already answered somewhere, i have not been able to find any reference to this.

**Comment by Raptor123471** [comment]
This is intended behavior for Spotify links. I currently do not know a way to extract audio directly from Spotify and it would also break their TOS rules putting your account at risk.

**Comment by Raptor123471** [comment]
Look at the pinned issue #50 for playing 18+ songs/videos. I can help you further here if you can't figure it out.
