### ISSUE TITLE
How can I make the bot always online using the uptimerobot?

### ISSUE THREAD

**Issue by Padin11** [Raptor123471/DingoLingo#78]
I would like to make the bot online using the uptimerobot, but if you have any other suggestion...

**Comment by Raptor123471** [comment]
You will need to be more descriptive in your issue. I am not sure what you are trying to accomplish.

**Comment by jkapi** [comment]
UptimeRobot is only monitoring software to check if something is alive. If you want to check if the bot is online, I think it's easiest to create a plugin that sends a heartbeat every once in a while to UptimeRobot.
