### ISSUE TITLE
Issue with queuing a spotify playlist.

### ISSUE THREAD

**Issue by Alchameth** [Raptor123471/DingoLingo#79]
When I queue a spotify playlist, the bot does not start playing immediately, rather just joins the voice chat and only shows its playing but actually isn't. To rectify this, i usually just queue the first song of the playlist and it just works

**Comment by Raptor123471** [comment]
May be related to #80 Can you post the error output from the console?

**Comment by nclsdllt** [comment]
Not sure if it is a related issue but when I try to play a Spotify playlist it does not launch. When typing the command again it usually works but I now have the playlist twice in my queue.
The console doesn't show any errors.

**Comment by nclsdllt** [comment]
Thanks a lot for the quick update, the new branch solved the issue for me. Spotify playlists are working perfectly
